### ISSUE TITLE
`eslint.lintText` returns an empty array

### ISSUE THREAD

**Issue by ton03** [robinloeffel/rollup-plugin-eslint#2]
https://eslint.org/docs/developer-guide/nodejs-api#-eslintlinttextcode-options

An error would be caught initially on the `result.warningCount` check

Would it be naive to just `return null;` when `result` is `undefined` or when `results` is empty? For me it works.

**Comment by rbnts** [comment]
In what case would eslint return an empty array? If, for example, you lint an empty file, it'll return an array looking something like this:

```js
[{
  filePath: x,
  messages: [ x ],
  fixableErrorCount: 0,
  fixableWarningCount: 0,
  errorCount: 0,
  warningCount: 0,
  output: undefined,
  source: undefined,
  usedDeprecatedRules: { x }
}]
```

Meaning `result` should never be `undefined`, as far as I know.

**Comment by ton03** [comment]
I may have found the root cause.

The documentation for [`eslint.lintText`](https://eslint.org/docs/developer-guide/nodejs-api#-eslintlinttextcode-options) says:

> If the options.filePath value is configured to be ignored, this method returns an empty array.

Where the error occurs when linting this file for example: `lib/config/something.ts`, and my `.eslintignore` has `config` instead of `/config` -- I only meant to ignore the `config` dir from the root.

Perhaps the plugin needs to respect `.eslintignore` and combine with `filterExclude`? And as a failsafe, just pass when `results` is an empty array since the file from the path is meant to be ignored?

**Comment by rbnts** [comment]
Hey man, sorry for the long wait! Since you've posed your question, the plugin has been rewritten to use the `load` instead of the `transform` hook and now utilizes the `lintFiles` method. Does this still happen?

**Comment by danimoh** [comment]
Hello Robin.
Yes, I can confirm that this issue still exists.
I'm using your eslint plugin in combination with `rollup-plugin-polyfill-node` which polyfills node builtins like `Buffer` for the browser.
However, unfortunately it also seems to register dummy files for the polyfills which do not actually exist but which eslint tries to operate on.
I tried ignoring these files via both, the eslintrc and your `filterExclude` option ~~which seems to correctly ignore the files~~.
However, eslint still emits an error for the non-existent file's glob pattern which does not match a file, see https://github.com/eslint/eslint/blob/cb27b0abeda6dfee55dd43b9cbe12afad321f55d/lib/cli-engine/file-enumerator.js#L317.
This error can be silenced by setting the option `errorOnUnmatchedPattern: false`.
However, the result of this is, that `lintFiles` does not return a result, leading to the same error described in this issue.

Update: the `filterExclude` option did actually not correctly exclude the file, as the glob pattern failed to match the file name of the virtual polyfill module which includes a `:`, even for glob pattern `**`.
I managed to fix the issue for me using a regex instead (see https://github.com/robinloeffel/rollup-plugin-eslint/issues/6).
This issue still holds though.

**Comment by rbnts** [comment]
Hey @danimoh, @ton03 

I've just pushed an update with several updated dependencies and also added a test case for you guys. I wasn't able to reproduce your issue anymore, so I'd be really happy if you could verify whether it's gone or not. If not, please provide me with a small snippet, so I could easily and directly see what's going on.

While developing, I've got those cases covered:
- File excluded via `.eslintignore`
- File excluded via `filterExclude`
- File excluded via bot `.eslintignore` and `filterExclude`

Those were my results (with additional logging to understand what's what):
<img width="1082" alt="Screenshot 2021-04-25 at 17 01 47" src="https://user-images.githubusercontent.com/6851646/115998991-3bd9ec80-a5ea-11eb-8122-a5aa72c5bca0.png">
<img width="1082" alt="Screenshot 2021-04-25 at 17 00 41" src="https://user-images.githubusercontent.com/6851646/115998988-39779280-a5ea-11eb-9af5-615e393128bc.png">

**Comment by rbnts** [comment]
I'll close this due to inactivity.
