### ISSUE TITLE
Fix only the output not the input

### ISSUE THREAD

**Issue by marcofugaro** [robinloeffel/rollup-plugin-eslint#3]
Hey, great plugin, it reads the eslint config correctly.

However I'm using it with the `fix` option, and weirdly enough it also fixes the input files in the `src/` folder.
Is there any way I can tell it to modify only the bundle outputted by rollup?

**Comment by rbnts** [comment]
ESLint assumes you want to lint and fix things in your source code. Meaning that (as of now) there is no way to circumvent this behavior, as this gets handled by ESLint itself. This also isn't part of any integration, be it [gulp-eslint](https://github.com/adametry/gulp-eslint), [eslint-loader](https://github.com/webpack-contrib/eslint-loader), or anything else, and probably won't be until there is an elegant way to achieve modifying the output but not the source, via the [Node.js API](https://eslint.org/docs/developer-guide/nodejs-api).
